### ISSUE TITLE
Invalid ``GetDataset`` Response Error is not Helpful.

### ISSUE THREAD

**Issue by acederberg** [Kaggle/kagglehub#160]
Hi! 

Thank you for this library. I found a bug that I'd like to offer to fix. When credentials are not correctly set, the following code

```python
import contextlib
import io
import pathlib

import kagglehub

DIR = pathlib.Path(".").resolve()

# NOTE: The ``path`` argument does not specify the path downloaded to, but
#       instead a subpath of the data.
DATA_DOWNLOAD_IO = io.StringIO()
DATA_ID = "anthonypino/melbourne-housing-market"
DATA_DIR = pathlib.Path(kagglehub.dataset_download(DATA_ID))
```

raises the error

```stderr
Traceback (most recent call last):
  File "/home/adrian/quarto/temp.py", line 13, in <module>
    DATA_DIR = pathlib.Path(kagglehub.dataset_download(DATA_ID))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/quarto/.venv/lib/python3.12/site-packages/kagglehub/datasets.py", line 28, in dataset_download
    return registry.dataset_resolver(h, path, force_download=force_download)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/quarto/.venv/lib/python3.12/site-packages/kagglehub/registry.py", line 23, in __call__
    return impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/quarto/.venv/lib/python3.12/site-packages/kagglehub/http_resolver.py", line 43, in __call__
    h.version = _get_current_version(api_client, h)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/quarto/.venv/lib/python3.12/site-packages/kagglehub/http_resolver.py", line 177, in _get_current_version
    raise ValueError(msg)
ValueError: Invalid GetDataset API response. Expected to include a currentVersionNumber field
```

It would appear that the library does not catch the ``401`` response from the API. In my case, the value of ``json_response`` is

```python
{'code': 401, 'message': 'Unauthorized access'}
```

It would be better to give another error message instead of saying that the response is malformed, e.g. just say ``401 Unauthorized``.

**Comment by acederberg** [comment]
I would also like to say that I am aware that this is the result of not having proper configuration and is a user error, however it was not optimal to have to debug from this message.

**Comment by calderjo** [comment]
Hi this was an issue internally which didn't let non logged-in users access to dataset download. 
It has since been resolved.

will closed this issue, but you can re-open if you believe the issue still persists
